### ISSUE TITLE
Create a more generic coordinates object for chimera and pegasus

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dwave_networkx#113]
There are now three different labeling systems for Pegasus
* linear: see https://github.com/dwavesystems/dwave_networkx/blob/dae190a5530d9f06fca89bf7e3737c06c7e6ab5a/dwave_networkx/generators/pegasus.py#L460
* pegasus: see https://github.com/dwavesystems/dwave_networkx/blob/dae190a5530d9f06fca89bf7e3737c06c7e6ab5a/dwave_networkx/generators/pegasus.py#L479
* 'nice' as introduced in #95 and revised in #106 

So we need a many-to-many translator.

One approach suggested by @boothby would be something like (using grids as an example):
```
>>> f = grid_coordinates.from_xy(shape=(10, 10)).to_linear()
>>> f(0, 0)
0
```

This should also support chimera and pegasus. So something like
```
>>> f = pegasus_coordinates.from_chimera(shape=(16, 16, 4)).to_nice(t=1)
>>> f(0, 0, 0, 0)
(1, 0, 0, 0, 0)
```

**Comment by arcondello** [comment]
Another approach was provided by @joseppinilla as part of https://github.com/dwavesystems/dimod/pull/460. See https://github.com/dwavesystems/dimod/pull/460/files#diff-03fca389ac2a33bd03a720399e336e2dR163

**Comment by joseppinilla** [comment]
I like @boothby's approach to interact with the converter, I think it's great.

In my approach I'm more interested in the way the coordinate_converter is obtained from an existing sampler or graph.

Part of the solution would be, as you mentioned in  [dwavesystems/dimod#460](https://github.com/dwavesystems/dimod/pull/460), to have the `topology` property carry everything we need to build it. And... from what I've seen, I think we would need `family`, `shape`/[`columns`,`rows`,`tile`], and `labels`
