### ISSUE TITLE
rectangular chimerae with coordinate-labeled nodes are bupkis

### ISSUE THREAD

**Issue by boothby** [dwavesystems/dwave_networkx#149]
**Description**
Something's up with the chimera graph generator, so that coordinate-labeled non-square graphs are not isomorphic to their integer-labeled friends.

**To Reproduce**

    import dwave_networkx as dnx
    h = dnx.chimera_graph(2,1,2)
    g = dnx.chimera_graph(2,1,2, coordinates=True)
    assert(h.number_of_nodes() == g.number_of_nodes())

**Expected behavior**

The graphs should be isomorphic (the above should not raise an  AssertionError)

**Environment:**
dwave_networkx 0.8.3

**Comment by boothby** [comment]
fixed in #150

**Comment by arcondello** [comment]
closed by #150
