### ISSUE TITLE
node_size failing in draw_embedding

### ISSUE THREAD

**Issue by joseppinilla** [dwavesystems/dwave_networkx#159]
**Description**
calling `draw_chimera_embedding` or `draw_pegasus_embedding` with `node_size` parameter results in:
`
TypeError: draw() got multiple values for keyword argument 'node_size'
`

**To Reproduce**
``` python
import networkx as nx
import dwave_networkx as dnx

G = dnx.chimera_graph(2, 2, 4)
H = nx.complete_graph(5)
emb = {0: [20, 19], 1: [18, 23], 2: [21], 3: [22, 16], 4: [17]}

dnx.draw_chimera_embedding(G,emb,H,node_size=100,overlapped_embedding=False) #Fails

dnx.draw_chimera_embedding(G,emb,H,node_size=100,overlapped_embedding=True) #Fails
```

**Expected behavior**
It should be possible to specify a node_size to pass down to the `draw` method.

**Environment:**
Any.

**Additional context**
Fix proposed in PR #158

**Comment by arcondello** [comment]
Closed by #158 , thanks for the PR!
