### ISSUE TITLE
pegasus_to_linear should throw error on negative z input

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave_networkx#167]
**Description**
Horizontal qubits are internally coupled to a vertical qubits according to the formula   
![image](https://user-images.githubusercontent.com/34041130/80813248-8b740c80-8b7e-11ea-9e55-d5fc022671d9.png)
which can produce a negative  value of `z` for the top-left Pegasus cell; for example, qubit 0: `(0, 0, 0, 0) --> (1, 0, 8, -1)`.
Applications that scan through qubits to find coupled qubits might use that and get a wrong node: 
```
>>> dnx.pegasus_coordinates(6).pegasus_to_linear((1, 0, 8, -1))
399
>>> dnx.pegasus_coordinates(6).linear_to_pegasus(399)
(1, 0, 7, 4)
```

**To Reproduce**
Use the formula above to find qubits internally coupled to node 0 on a Pegasus chip.

**Expected behavior**
An error for coordinates that are out of range 0<=u<2, w, z => 0, 0<=k<12. 

**Environment:**
 - OS: All
 - Python version: All

**Additional context**
I expect other of the coordinate transformation utilities need input checks too.

**Comment by boothby** [comment]
I respect the desire for rigour, but disagree with this from a design perspective.  The goal of these functions is to provide a very fast translation between coordinate systems.  Introducing this sort of checking will significantly slow down the translation process (by a factor of 2 according to a test I just ran in py3.6), which I'm uncomfortable with.

**Comment by JoelPasvolsky** [comment]
So I'm hearing that we'll implement *_s safe functions for all of these? :-)
