### ISSUE TITLE
Mention coloring function similarity to binary CSP

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave_networkx#64]
Alex Condello [5:07 PM]
I was working on my presentation for tomorrrow and it occured to me that dnx has a graph coloring function that could be compared to the binarycsp approach. Might be worth a mention in the docs at least

**Comment by Arafatk** [comment]
Hi,
@JoelPasvolsky  [This line](https://github.com/dwavesystems/dwave_networkx/blob/master/dwave_networkx/algorithms/coloring.py#L58) mentions the neighbor constraint as defined in [the paper](https://www.dwavesys.com/sites/default/files/Map%20Coloring%20WP2.pdf) so yes this is a classic Binary CSP.     
Is it cool if I send a small pr to mention this in the docs?

**Comment by JoelPasvolsky** [comment]
Hi @Arafatk, please do. You can see some guidelines here: http://dw-docs.readthedocs.io/en/latest/CONTRIBUTING.html
Thanks!
