### ISSUE TITLE
Question - Samplers for max clique

### ISSUE THREAD

**Issue by pbanavara** [dwavesystems/dwave_networkx#68]
Hey everyone - Perhaps a noob question. I am looking to implement max clique on the DWave annealer.  I need to pass a sampler to this method:

`def maximum_clique(G, sampler=None, lagrange=2.0, **sampler_args):`

When I check the dimod module,  I only find the abstract class Sampler and in the examples the simulatd sampler is used. Does this mean I have to implement a new Sampler in order to use the maximum_clique method ? Please let me know. 

If this is not the appropriate place to ask this question, please close this issue and point me to another location perhaps SO.

**Comment by arcondello** [comment]
Hi @pbanavara ,

dimod provides a sampler API. Any sampler which uses that API should work with a dwave-networkx algorithm.

There are several samplers that we have implemented in several different packages. You can see our list of packages https://dw-docs.readthedocs.io/en/latest/projects.html#projects

The noteable ones are `ExactSolver` in dimod, `DWaveSampler` in dwave-system, and `SimulatedAnnealingSampler` in dwave-neal.

Hope this helps!

**Comment by pbanavara** [comment]
@arcondello  Thanks much. I am now using the DWaveSampler with my credentials. Any idea what's the maximum size of the graph that I can embed using this sampler. Also does the graph have to be fully connected ?

**Comment by arcondello** [comment]
You might find https://dw-docs.readthedocs.io/en/latest/examples/max_cut.html#max-cut useful as an example.

Also you'll need to embed your graph (use the `EmbeddingComposite` as in the above example). The largest complete graph that can be embedded is K65.

**Comment by pbanavara** [comment]
Great ! Thanks @arcondello I was missing the Embeddingcomposite step. Will reach out to you if I come across any more issues. So looks like the graph need not be fully connected or complete. I am trying out with all variants and so far if I stay under 40 nodes, I am good.

**Comment by arcondello** [comment]
Glad to hear it, good luck!
