### ISSUE TITLE
Add existing hardware architectures

### ISSUE THREAD

**Issue by mstechly** [dwavesystems/dwave_networkx#75]
**Current Problem**
It is not obvious how to find what is the exact architecture of the existing D-Wave machines and how to express it using `chimera_graph` method.

**Proposed Solution**
Chimera graphs of the existing machines could be added as separate methods. A `dwave_machines.py` file could be added with definitions of graphs of D-Wave 2X, D-Wave 2000Q and possibly also proposed Pegasus machines.
It could include the hardware impurities.

**Alternatives Considered**
Alternatively, there could be information in readme about architectures implemented in hardware.

**Comment by arcondello** [comment]
This is a good idea, I think my preference would be to only encode this information in documentation, @JoelPasvolsky ?

For now
```
# D-Wave 2X
C = dnx.chimera_graph(12, 12, 4)

# D-Wave 2000Q
C = dnx.chimera_graph(16, 16, 4)
```

**Comment by mstechly** [comment]
I made a PR: #77
